### ISSUE TITLE
use terms header field and header section

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#101]
From the mailing list:

From: Stan Kalisch <stan@glyphein.mailforce.net>
Message-Id: <8B35955B-C77A-44FE-9CDB-872FBF6C3B10@glyphein.mailforce.net>

Minor point:  should not the terms "header field" and "header section" be used as in RFC 5322?

Stan

**Comment by neilj** [comment]
I can't find "header field" anywhere in the spec anymore, so this is no longer relevant.

**Comment by skalisch** [comment]
A number of RFCs subsequent to RFC 5322 hew to these terms as conventions, presumably for a clarity of syntax across specs.  In any event, whatever you decide, you should also resolve the usage of these kinds of terms in the implementation guide at http://jmap.io/server.html.
