### ISSUE TITLE
Investigate token binding and interaction with JMAP

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#107]
From IETF99 notes - it's probable that token binding is just going to be a way an authentication token is protected from exfiltration and JMAP might either automatically get the benefits if the server/client support it without requiring any special support, or it may need some text added to the spec to require/use it.

This ticket is just to investigate what is involved and make a determination if more work is required and/or if it's in scope.

**Comment by neilj** [comment]
We've removed authentication from the spec so this is definitely not in scope.
