### ISSUE TITLE
Using HTTP as a transport

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#111]
Even if we keep using HTTP as a tunneling protocol, there may be things HTTP could build that would make future JMAP-ish protocols more able to use HTTP.  We should detail exactly what we would need from HTTP if we were to do JMAP differently for the benefit of the HTTP folks.

**Comment by neilj** [comment]
Had a good chat with Mark Nottingham about the constructs we're using and why. We agreed there is unlikely to be easy ways of achieving all of what JMAP does purely through HTTP constructs. He is going to review the JMAP core spec and will open GitHub tickets if there are any things he thinks needs review or might help influence the evolution of HTTP in the future.

**Comment by cjnewman** [comment]
My view on this: HTTP is primarily a request/response protocol. IMAP is a cache/update protocol (a very different model where client commands trigger cache updates that may or may not be related to the command issued). JMAP is trying to be what I'd call a request/response update protocol -- where the client describes exactly the updates it wants. That's going to be easier for client authors and protocol reviewers to understand than the IMAP model, but that model does not fit the REST/HTTP model well once the description of the updated information the client needs gets the expressiveness necessary for minimal round-trips. CardDAV & CalDAV attempt something similar, but this is already a complex problem and layering on WebDAV adds a lot of unnecessary complexity.
