### ISSUE TITLE
change fetchRecords to be a getFoos with default accountId and ids

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#121]
3.10.2 getFooUpdates

fetchRecords & fetchRecordProperties

Instead of two separate parallel properties, how about defining fetchRecords as having the same structure as a getFoos object, but with appropriate defaults for accountId and ids. This way, extensions to the getFoos object naturally apply to the fetchRecords value object.

**Comment by neilj** [comment]
This was resolved by ac46f53a as there are no longer fetchRecords arguments to make implicit calls, but instead you can make explicit calls using back references for arguments to use the result of a previous one.
