### ISSUE TITLE
JMAP Emailer object from IMAP address without host?

### ISSUE THREAD

**Issue by jtmoulia** [jmapio/jmap#13]
The JMAP spec has an example Emailer object:

```
[
    {name:"Joe Bloggs", email:"joeb@example.com"},
    {name:"", email:"john@example.com"}
]
```

Over IMAP, the JMAP `email` field can be constructed by joining the IMAP `addr-mailbox` and `addr-host`. However, in certain common cases (e.g. Mandrill, GCal invites) the `addr-host` isn't present. What should the behavior be in this case?

See [Switchboard #51](https://github.com/thusfresh/switchboard/issues/51).

Thanks!

**Comment by neilj** [comment]
I'm a bit confused about when you might see this case in GCal invites? But regardless, I think the behaviour in this case should always be:

    email := addr-mailbox . @ . addr-host

So if you only had the mailbox, you would get something like:

    { name: "Joe Bloggs", email: "joe@" }

Does that answer your question? I'm happy to clarify this in the spec if so.

**Comment by jtmoulia** [comment]
Yup, that answers my question. It wouldn't hurt to mention this possibility in the JMAP spec so clients are aware that no host is a case they might need to handle.

Thanks!
