### ISSUE TITLE
RFC 5322 empty group syntax in Emailer object

### ISSUE THREAD

**Issue by cjnewman** [jmapio/jmap#131]
While RFC 5322 group syntax is rarely used to actually group addresses (and is thus fine to discard when used that way, IMHO), the empty-group syntax is used and often contains useful information in the group name. I suggest converting an empty group to an Emailer object with this form:
{"name":"group-name", "email":""}
A quick search of my email does find mail with "undisclosed-recipients:;" in the "To:" header sent this year.

**Comment by neilj** [comment]
Closing as duplicate of #59 (I've copied your comment across).
