### ISSUE TITLE
clarify whether uptoMessageId is included in the response

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#149]
(of course it won't be called MessageId by then either)

The wording right now is very unclear:

uptoMessageId: String|null The message id of the last message in the list that the client knows about. In the common case of the client only having the first X ids cached, this allows the server to ignore changes further down the list the client doesn’t care about.

...

If an uptoMessageId was given AND this id was found in the list, only messages positioned before this message that were removed need be returned.

...

The first of these implies that uptoMessageId is one that the client knows about, yet the second thing (in the "removed" description) says "positioned before", implying that you don't need to tell about the uptoMessageId being deleted!

**Comment by neilj** [comment]
This now reads:

> If the sort and filter are both only on immutable properties and an *uptoId* is supplied and exists in the list, any ids that were removed but have a higher index than *uptoId* SHOULD be omitted.
