### ISSUE TITLE
position in getMessageList response should be defined by messages, not threads

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#151]
The response section says:

position: Number The 0-based index of the first result in the threadIds array within the complete list.

But this is wrong, particularly if collapseThreads is false.  It should be the position of the first result in the messageIds array.

**Comment by neilj** [comment]
This is not a special case any more, but just an instance of "getFooList" so this is no longer a problem.

(The definition in getFooList is *The 0-based index of the first result in the `ids` array within the complete list of results.*)
