### ISSUE TITLE
Allow partial updates of the keywords object.

### ISSUE THREAD

**Issue by chibenwa** [jmapio/jmap#152]
One very sad thing the we miss while designing the **keyword** message property is that we can not do partial updates of this property.

For instance, marking m1 as read needs:
 - Fetching keywords for m1 (latest updates)
 - The client should compute new state of m1
 - The client updates keywords property for m1

The bad points is:
 - Pushing concurrency management to the client
 - A read is often needed before updating the keywords property to reduce the risk of concurrent changes.

This means that, to safely handle concurrent **keywords** changes, the use of the **ifInState** SetMessages property, which makes an initial working subset of implementation of JMAP harder to reach. (Not to mention **ifInstate** applies globally to all the messages the request updates, and might have a new value even if there is no conflict on the given Keywords...)

What I propose is to change the keyword semantic. In an update:
 - a keyword associated with `true` will be added to the message keywords properties.
 - a keyword associated with `false` will be removed from the message keywords.

For instance to mark a message as seen and flagged, you can do this:

```
[
	["setMessages", {
		"update": {
			"messageId": {
				"keywords": {
					"$Seen": false,
					"$Flagged": true
				}
			}
		}
	}, "#0"]
]
```

(It allow some kind of unit access to each keyword the way isFlag, isAnswered, is\* did).

**Comment by neilj** [comment]
I agree we need to be able to do this, but I have a different syntax which I think is better:

```json
[["setMessages", {
	"update": {
		"messageId": {
			"keywords/$Seen": null,
			"keywords/$Flagged": true
		}
	}
}, "#0"]]
```

This uses [JSON Pointer syntax](https://tools.ietf.org/html/rfc6901) and aligns with the work done for occurrence overrides in the [JSCalendar](https://datatracker.ietf.org/doc/draft-jenkins-jscalendar/) format, which will be hopefully what JMAP Calendar uses.

**Comment by neilj** [comment]
(Should have mentioned, but this is better because clients have the option of either replacing all keywords, or just setting/unsetting some, and it extends trivially to deeper hierarchical objects so is more generic).

**Comment by chibenwa** [comment]
I guess this JSON pointer notation can also be used for mailbox ids? (ie copy)

**Comment by neilj** [comment]
Yes. mailboxIds is going to change from an array to an object the same as keywords, and my intention is the patch semantic is generically available for updates, so you would automatically be able to use it for mailboxes too.

**Comment by chibenwa** [comment]
http://jmap.io/spec-core.html#use-of-null

```
When updating an object in a setFoos style call, a missing property MUST be interpreted as the existing value for that property (i.e. don’t update it).
```

So with your proposal, we now have confusion on what is expected from a request, if a missing property has a different meaning than setting this prop to null...

Eg. in the provided example, "keywords/$Seen": null, should behave exactly like a request without $Seen flag set, and that's probably not what we want.

By setting it explicitly to **false** we avoid such confusion, without losing semantic, isn't it?

**Comment by neilj** [comment]
I've clarified all this in the pull request, see [these](https://github.com/jmapio/jmap/pull/148/commits/4f30cb2609c6a5cf8e68b65569f99c9a342ab724) [commits](https://github.com/jmapio/jmap/pull/148/commits/e86ff38c952d7f7f2d842afd1826a1f0b50d5427) for clarification of omitting properties and [this commit](https://github.com/jmapio/jmap/pull/148/commits/da93735ecca6c63e1c366180c442656a340e1d9e) for the patch syntax.

> By setting it explicitly to false we avoid such confusion, without losing semantic, isn't it?

This doesn't work for two reasons:
1. Either `{ "keywords": { "foo": true }}` is ambiguous or you can't replace the whole keywords property anymore.
2. This syntax is just focussed on keywords. The patch syntax I propose is generically available for all objects; some of which may have boolean properties you want to set to false! This is going to be particularly important with calendar events (e.g. setting the participation status of one attendee to an event).
