### ISSUE TITLE
Optional {name} parameter in download URL is unclear

### ISSUE THREAD

**Issue by robn** [jmapio/jmap#16]
From the spec:

> The URL endpoint to use when downloading files, in RFC6570 URI Template (level 1) format. The URL MUST contain a variable called blobId. The URL SHOULD contain a variable called name. The client may use this template in combination with a blobId to download any binary data (files) referenced by other objects. Since a blob is not associated with a particular name, the template SHOULD allow a name to be substituted in as well; the server will return this as the filename if it sets a Content-Disposition header. 

But, RFC6570 Level 1 has no provision for optional parameters. The proxy URL structure is `/raw/{userId}/{blobId}/{name}`. If I don't have a name, I can't usefully expand that template.

I think Level 3 and '{?var}' is what's needed for this case:

`/raw/{userId}/{blobId}{?name}`

I don't think the spec itself needs to change other than to remove the "Level 1" requirement. Which does raise the bar a bit for clients, but there seems to be plenty of libraries available; one quick search finds [this list](https://code.google.com/p/uri-templates/wiki/Implementations).

**Comment by neilj** [comment]
It's not an optional parameter (a parameter for which you may optionally pass a value), it's a parameter that may optionally be included in the template string. The client always has a name (or can make one up if it really has to), but the server may not support inserting this into the URL. So the template is still Level 1 either way.

**Comment by robn** [comment]
Well, I did say "unclear"... ok :)

**Comment by neilj** [comment]
Yeh, the spec could probably be made clearer. Pull request…? :D

**Comment by robn** [comment]
Bah, that's my line. Ok, will do :)
