### ISSUE TITLE
Pluralise the object names in all methods

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#164]
e.g. getUpdatesToMailboxes rather than getMailboxUpdates

**Comment by dehart** [comment]
Here is an idea:

getFoos -> foo.get
setFoos -> foo.set
getFooUpdates -> foo.getUpdates
getFooList -> foo.getList
getFooListUpdates -> foo.getListUpdates

**Comment by brong** [comment]
@dehart as an implementor in a language where . isn't valid in method names, I would find that harder to map directly.  Right now I have this:

    my ($command, $args, $tag) = @$item;
    my $FuncRef = $api->can($command);

And if $FuncRef exists, then the API supports that method.  with . in the name, I would have to translate the command before to find the method name.

**Comment by dehart** [comment]
I was thinking of implementing it like this:

`class Foo {
  function getList();
  function getUpdates();
  etc..
}
($foo, $method) = $command.split('.');
$foo::$method($args);
`

We could replace the separator with something valid before mapping to a method as well.
