### ISSUE TITLE
Explain how to handle renaming a=>b and b=> a in Foo/set

### ISSUE THREAD

**Issue by neilj** [jmapio/jmap#176]
The validity of a Foo object may depend on the state of other Foo objects. For example, Mailbox#name + Mailbox#parentId must be a unique combination (you can't have two mailboxes with the same name inside the same parent).

JMAP allows you to supply a set of changes such that the final state is valid, but may have invalid intermediate steps when processed sequentially (e.g. you have mailbox A and mailbox B and you rename A -> B and simultaneously B -> A).

Further explanation is required to clarify how servers are meant to handle this. Suggestion is
1. Each /set is a transaction (by current JMAP definition)
2. Creates/updates/destroys are each considered individually and each succeeds or fails (as per the spec, you can't commit part of a change to a specific record, but can commit changes to some records but not others).
3. When processing, if a conflict that depends on overall state of the type being processed is found, allow the change but set a flag.
4. At the end, if the flag is set check the state is now valid before committing. If not valid, throw away the transaction and start again, but this time immediately reject (with the appropriate error) any change that individually would result in an invalid state.

Refinements on this explanation welcome.

**Comment by rsto** [comment]
For me, points 1 and 2 really mean two different things: either a create/update/destroy is a single atomic unit, or a /set is.

Point 1 bears in my opinion the following risks:

- Less sophisticated implementation might choose to hold one lock across all Foo objects for the duration of the /set method to comply. Consequently, they may set `maxObjectsInSet` defensively low to handle (probably) rare cases.
- Even if an implementation implements the strategy of points 3 and 4, or a similar scheme like splitting the /set operations in conflicting and non-conflicting operations, a /set could still degenerate to a single transaction. The only way to protect from this in the general case is again `maxObjectsInSet`.

What are the cases where invalid states can occur? For the JMAP mail types, three scenarios come to my mind (all scoped to one /set):

- Mailbox renames: swap names of sibling mailboxes
- Mailbox role: swap roles of two mailboxes
- Mailbox moves: swap mailboxes in the mailbox tree such that the interim state would cause a loop where the final state wouldn't.

Which suggests to me that there is just a small subset of JMAP object types that require interim states, and also just require transactions in special circumstances.

So why not support the special case with a special flag? E.g. couldn't a `transactional` boolean argument on the /set object indicate what the client wants? Then clients can easily send a /set including lots of mail changes in one go, which cannot ever result in interim states. Whereas for structural changes of the mailbox tree, they set the transaction flag and need to comply with, say, a new `maxObjectsinSetTransaction` setting.

**Comment by neilj** [comment]
> Less sophisticated implementations might choose to hold one lock across all Foo objects for the duration of the /set method to comply.

I'm not sure I follow your concern here. You need to hold a lock across the set of Foo types *for the account the /set is operating on* to comply with the concurrency guarantees JMAP already specifies.

**Comment by rsto** [comment]
> I'm not sure I follow your concern here. You need to hold a lock across the set of Foo types for the account the /set is operating on to comply with the concurrency guarantees JMAP already specifies.

Yes, I meant account-scoped locks to this object type. Which, depending on the implementation, could also mean an implicit lock on other object types of that account.  E.g. For Cyrus, we need to lock mailboxes for mail writes, but that mailbox might be temporarily locked in a transactional Mailbox/set. Consequently we'll have to trim `maxObjectsInSet` to a conservative number. That number will be driven by the Foo type that will incur the longest lock time, irrespective if other types are more lightweight.

If /set semantics are meant to stay as-is, I find the above explanation enough, though.
