### ISSUE TITLE
Foo/get "changes" result argument is unsafe in result references

### ISSUE THREAD

**Issue by rjbs** [jmapio/jmap#179]
I believe that we need to change the spec for Foo/changes.

> changed: String[]|null An array of ids for records which have been created or 
> modified but not destroyed since the oldState, or null if none.

Null should be illegal.  Here's why:

    [ "Foo/changes", { "sinceState": "123" }, "a" ],
    [ "Foo/get", { "#ids": { "resultOf": "a", "name": "Email/changes", "path":"/changed" } }, "b" ]

There are no changes to Foo since 123, so the response is:

    [ "Foo/changes", { "changes": null }, "a" ]

When the server evaluates the second sentence, it is effectively:

    [ "Foo/get", { "ids": null }, "b" ]

… rather than {"ids":[]}, which is semantically quite distinct!  It attempts to fetch all
Foos, which is wrong, and might lead to a resultTooLarge or worse.  Obvious options:

a. require Foo/changes's changes result argument to be an Array
b. add defaultIfMissing to result references

(a) seems simplest.

We should also consider whether any other variable-type return values have the same
type problems.

**Comment by dehart** [comment]
I'd like to propose a third option

Both `null` and `[]` should not return all Foos
Instead only return all Foos if no "ids" property is passed.
```
[ "Foo/get", {}, 'b' ]
```

Require "changed" and "destroyed" to be an Array as well. 
This way client developers do not need to check `if(changed !== null)` but can just loop the empty Array
