### ISSUE TITLE
Create a separate document (extending jmap-mail) for single-html body

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#193]
This is a body in which multiple parts have been concatenated together, converted to HTML, and non-text parts converted to data URIs within the HTML so there are no external resources to load.

IETF101 meeting decided this is better as a separate draft, and maybe consider merging back into main spec before publication if it seems right, but otherwise progress independently.  It has significant server complexity and security considerations.

**Comment by neilj** [comment]
IETF102: Shelved for now, as nobody interested.
