### ISSUE TITLE
Clarify client behaviors with respect to JMAP method-level errors

### ISSUE THREAD

**Issue by cjnewman** [jmapio/jmap#210]
The primary reason to have a machine-readable distinction between errors is because different client actions are appropriate for the different errors. The current text describing method errors is unclear about what the suggested client actions are with respect to the different errors.

The one I find most problematic is the "serverError" which says the server is in an undefined state. An undefined state suggests the only reasonable robust client response is to close the connection and start over with a full resync. I don't think that's a common case and that definitely shouldn't be the default behavior in response to an unknown error. The common case is the method was rejected for some persistent reason and no changes were made to server state.

I also think timedOut isn't great. While timedOut is one of the cases that most implementations will consider a temporary failure, not all timeouts are temporary, so the client action in response to this is unclear. Probably best to just replace this with a "temporaryError", where the client action is clear.

If having an error with semantics equivalent to current 'serverError' text is important, I suggest calling that new error 'partialFailure' and I wrote proposed text for that.

Here's a first attempt to clean this up:
---
serverError: An unexpected or unknown error occurred during the processing of the call. A description property should provide more details about the error. The method call made no changes to the server's state. Attempting the same operation again is expected to fail again. Contacting the service administrator is likely necessary to resolve this problem if it's persistent.

unknownMethod: The server does not recognise this method name.

invalidArguments: One of the arguments is of the wrong type or otherwise invalid, or a required argument is missing. A description property MAY be present to help debug with an explanation of what the problem was. This is a non-localised string, and is not intended to be shown directly to end users.

forbidden: The method and arguments are valid, but executing the method would violate an ACL or other permissions policy.

temporaryError: Some internal server resource was temporarily unavailable. Attempting the same operation later (perhaps after a backoff with a random factor) may succeed.

partialFailure: Some, but not all expected changes described by the method occurred. The client may need to re-synchronize impacted data to determine server state. Use of this error is discouraged.

accountNotFound: An accountId was included with the method call that does not correspond to a valid account, or accountId was null but there is no primary account for the capability that defines the data type.

accountNotSupportedByMethod: An accountId given corresponds to a valid account, but the account does not support this data type.

accountReadOnly: This method call would modify state in an account that has isReadOnly == true.
---

**Comment by neilj** [comment]
Thanks Chris, I've taken that and adapted it slightly. I've gone with `serverUnavailable`, `serverFail` and `serverPartialFail` – they're all prefixed by `server` as these are all errors in the server rather than in the request issued by the client. I've also changed the requirement for handling unknown errors to be the same as `serverFail` (no state changed on the server) rather than `serverPartialFail`.
