### ISSUE TITLE
Email/get header:asFoo in the face of failure?

### ISSUE THREAD

**Issue by wolfsage** [jmapio/jmap#217]
For many of the asFoo header types, the spec says something like:
````
To prevent obviously nonsense behaviour, which can lead to interoperability issues, this form may only be fetched or set for the following header fields:
````
It doesn't say what an implementation should do in the event of failure to parse or if someone attempts to use these forms on headers that they shouldn't be able to. Should we specify?

For example, it looks like cyrus just fills in null for each value that it would have attempted to parse.

That is, if you say "header:received:asDate:all" you'll get a list of NULLs for each received header.

**Comment by neilj** [comment]
This is [already specified](https://github.com/jmapio/jmap/blob/master/spec/mail/message.mdown#emailget):

> As specified above, parsed forms of headers may only be used on appropriate header fields. Attempting to fetch a form that is forbidden (e.g. `header:From:asDate`) MUST result in the method call being rejected with an `invalidArguments` error.

**Comment by wolfsage** [comment]
Ah, I see thanks.
