### ISSUE TITLE
New error codes

### ISSUE THREAD

**Issue by ksmurchison** [jmapio/jmap#231]
After adding support for RFC 7807 error responses to Cyrus JMAP, it looks like we may want additional codes to indicate that the request exceeds a server limit (e.g. maxSizeRequest) and that a creationId is invalid.  In both cases, a 'detail' element can contain additional info.

Also, for readability, should we hyphenate multi-word codes?  
E.g. not-json, not-request, unknown-capability

**Comment by ksmurchison** [comment]
Perhaps we need an unknown-method error as well.

**Comment by neilj** [comment]
Not sure what you mean by a "creationId is invalid", but that sounds like a method-level error.

I agree we probably want some kind of "exceeds limit" response when the whole HTTP request is rejected due to maxSizeRequest, maxCallsInRequest or maxConcurrentRequests constraints.
