### ISSUE TITLE
Body search behaviors with non-text parts, suggest they match IMAP

### ISSUE THREAD

**Issue by cjnewman** [jmapio/jmap#238]
IMAP's BODY search is allowed to search non-text parts. This behavior is deployed by some IMAP servers. I wrote some new text that I believe is pragmatic, IMAP-aligned, and makes JMAP body search more useful for end-users. I'm not sure if this merits discussion on the list.

See Pull request #237

**Comment by neilj** [comment]
I think this is fine. I've merged #237.
