### ISSUE TITLE
charset should be us-ascii if Content-Type header text/* but no charset defined?

### ISSUE THREAD

**Issue by wolfsage** [jmapio/jmap#243]
Per https://tools.ietf.org/html/rfc2046#section-4.1.2 (and similar to issue #216) if there is a Content-Type header of text/* but no charset, it is implicitly us-ascii.

The JMAP spec says, however:

````
charset: String|null The value of the charset parameter of the Content-Type header field, if present, or null if the header field is present but has no charset parameter. If there is no Content-Type header field, this is the implicit charset as per the MIME standard (us-ascii).
````

Should we leave it as null as the JMAP spec says or set it to us-ascii for text/* parts as the RFC says?

Cyrus is currently doing it two both ways, setting us-ascii in Email/get, and setting null in Email/parse.

Which way do we want to go with this? (See https://github.com/cyrusimap/cyrus-imapd/issues/2442)

**Comment by neilj** [comment]
Should be `us-ascii`. I've updated the spec.
