### ISSUE TITLE
Emails Example 4.10

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#263]
In the examples for fetching emails and thread in the Mail spec. [Here](https://jmap.io/spec-mail.html#examples) the request is calling 4 methods:

1. Email/query
2. Email/get
3. Thread/get
4. Email/get

The 2nd method `Email/get` returns data that is passed to `Thread/get`'s result reference
The 4th method `Email/get` returns data the client is using.

I noticed we could save some bandwidth by not returning the response of the 2nd method which I think is not used by the client (the same data is returned in the 4th method).
Also clients don't have to skip responses it is not using.

A way to achieve this could to to set `Invocation.client id` to `null`
What do you think?

**Comment by neilj** [comment]
We've [discussed this before](https://mailarchive.ietf.org/arch/msg/jmap/c3yjiPrfhNomPT46-X3fvJAnRvI) and the previous conclusion was that while this could be neat, it adds complexity (especially when proxying) which outweighs the minor benefits. I do like your suggestion for how this would be expressed syntactically were we to do it in the future though.
