### ISSUE TITLE
Core 5.3 SetError::properties

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#264]
For a SetError of type `invalidProperties` I noticed the following:

> The SetError object SHOULD also have a property called properties of type String[] that lists all the properties that were invalid.

It could also have a list of properties with a reason why they are invalid to show to the user. (required, too long/short, invalid date, etc) Or should all these validation errors be implemented on the client.

**Comment by neilj** [comment]
It's generally considered up to the client to validate data and display errors to the user; this avoids issues of localisation for a start.
