### ISSUE TITLE
EmailBodyPart RFC2045 Conent-Description

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#265]
I noticed that the `EmailBodyPart` object does not have a property for the MIME Content-Description
https://tools.ietf.org/html/rfc2045#section-8

Is there a reason this is not part of JMAP?

**Comment by neilj** [comment]
I don't think anyone thought it important enough to have its own property; I'm not sure it's really used anywhere in practice. You can still access it through the `headers` property on the `EmailBodyPart`.
