### ISSUE TITLE
formal (machine readable) protocol specification (e.g. openApi)

### ISSUE THREAD

**Issue by seriousme** [jmapio/jmap#287]
Hi,

are there any plans to create a formal (machine readable) specification for JMAP ?
E.g. if one would create an [openapi specification](https://en.wikipedia.org/wiki/OpenAPI_Specification) it would be possible to use tools to [generate clients and servers](https://openapi-generator.tech/), [test implementations etc](https://openapi.tools/)
Creation of the specification can be done in a variety of ways, e.g. generate spec from code or using a design-first approach. And once you have the formal spec you can generate documentation from it.

Kind regards,
Hans

**Comment by neilj** [comment]
No current plans. If you would like to contribute such a thing we would be happy to link to it from the jmap.io website however.
