### ISSUE TITLE
Non-technical advice

### ISSUE THREAD

**Issue by wulongji2016** [jmapio/jmap#294]
Non-technical advice
I don't know English, this is the text of software translation.
I saw the new version of https://www.ietf.org/about/participate/tao/
I am very happy to quote the "dao" of the Chinese Laozi. I did not expect foreigners to accept this concept.
I am from China and have a few suggestions. I hope that everyone will adopt it.
Technology is for people, so I mention a few non-technical suggestions.
In many countries and regions, the Internet is blocked, including many mainstream services (Facebook, twitter, Google whatsapp) can not be used. In WeChat or Weibo, you can't talk about sensitive topics. For example, democracy, freedom of the press. Otherwise, the information will be deleted. In serious cases, after the police find you, ask you separately or put you in jail. This is not a joke, it is a real situation.
This feeling, like the lack of a river in the desert, is lifeless.
Just like in a closed black room, you can't see the sun.

The reason is that these countries are authoritarian regimes. They are afraid of the public to understand the news and the truth, and they are worried about the unity of the people. These dictatorial rules smash and resist democracy and freedom.
The current technology is difficult for everyone to break through such a network blockade.

I can use VPN to break through the network blockade, but not everyone has the opportunity to use it. China's Apple App Store has removed all VPN software. Other Android app stores can't find VPN software. VPN is difficult for everyone. Use, so other ways are needed.

1) Resolving such dilemmas requires the help of various countries and international organizations. Establish a PtoP message communication method to effectively avoid network blockade. Mail is a way of PtoP. The downside of current mail is that there is too little support for video and audio, and it is recommended to add functionality.
A) You can insert and play videos in the body of the message. The video source can be an attachment or a third-party URL.
B) It is very simple to directly play the video inside the attachment.
C) Mobile mail and computer mail display have the same effect.

This can easily spread video to other people, help break through the network blockade, bring more real reports of various events to more people, spread democratic views, and facilitate free exchanges.
2) Support email content and sender address and recipient address encryption to avoid third party monitoring. The Chinese network listens to all the information and is very unsafe.
3) The protocol supports the distinction between spam and subscription mail. Mail increases the function of preventing spam. If it is spam, you can simply report it and add a report button (distinguish between spam, subscribed email, regular email, etc.) in front of the header of the email. I hope the new email protocol supports spam reporting. If you are an email that you like to subscribe to, please indicate your subscription, even if the other party sends more emails, it will not be marked as spam.

The organizers of the mail agreement, you work in a free country, and the network is open. It is difficult for you to understand the situation of people in countries like China or North Korea or Iran.
In the area under the rule of Nazi Germany, there was a very famous "White Rose Leaflet", which was written by several people such as Hans Scholl. They sent flyers to the mailbox of the house. Such a spirit is worth learning. They resist the authoritarian government, awaken the conscience of the people, and call on everyone to unite to fight the Nazis. The flyers play a very important role. (https://en.wikipedia.org/wiki/White_Rose)

I hope that you will contribute to your efforts to resolve the network blockade of the authoritarian state out of the humanitarian spirit.
Pursuing freedom and democracy, pursuing the truth of the news is the power everyone should have. I hope that you can help us, thank you!

**Comment by neilj** [comment]
We appreciate your feedback, and sympathise with the issues. This is beyond the scope of JMAP to solve however.

**Comment by wulongji2016** [comment]
1) I want to discuss with you, which are within the scope of your work?
In the mail, you can send HTML content. Who made these specifications?
Now HTML can display images, but can't display sounds and videos.
Mail is more than just text, it should support richer media resources.
The browser does not support video many years ago, but it is now supported, and this is progress. I hope that the mail agreement will develop and progress as well.
