### ISSUE TITLE
Who's using JMAP?

### ISSUE THREAD

**Issue by chmac** [jmapio/jmap#310]
Would be great to add a list of "who's using JMAP" either to the site or somewhere here on GitHub.  I'm assuming that folks besides FastMail are deploying it and it'd be great to see who they are to get a better sense of what adoption looks like.

**Comment by marclaporte** [comment]
See here: https://jmap.io/software.html

And some here: https://www.openhub.net/tags?names=jmap

**Comment by marclaporte** [comment]
https://github.com/jmapio/jmap/pull/313
