### ISSUE TITLE
From Cyrus: use of EmailSubmission/set#onSuccess* without :mail capability

### ISSUE THREAD

**Issue by brong** [jmapio/jmap#311]
https://github.com/cyrusimap/cyrus-imapd/issues/2958

If you only send:

```
    "using": [ "urn:ietf:params:jmap:submission" ]
```

Then when the implicit `Email/set` gets called, it returns an `unknownMethod` error.  The spec isn't entirely clear on what should be done here: reject the EmailSubmission as well?  Automatically add `:mail`?

**Comment by neilj** [comment]
I believe the current behaviour is correct, although it probably should be made more explicit if we have a rev2 spec. The behaviour is specified as an implicit call to `Email/set` after the `EmailSubmission/set` call completes. The result of that method should be the same as if it were called explicitly, so without the require you get an `unknownMethod` error response.
