### ISSUE TITLE
Require "urn:ietf:params:jmap:mail" capability when calling MDN/set?

### ISSUE THREAD

**Issue by cketti** [jmapio/jmap#314]
This is similar to #311. 

We could require `MDN/set` to add the "urn:ietf:params:jmap:mail" capability in the `using` property of the request because of the implicit call to `Email/set`. Failing to provide the capability would return a `unknownMethod` error response for the implicit call.

However, using this approach could allow a client to send multiple MDNs because the `$MDNSent` keyword isn't added to the message and that keyword is used as rejection criterion by the server.

If this is unwanted behavior, I see the following two options to forbid it:
- require both capabilities for the `MDN/set` call, i.e. `MDN/set` will fail when the "urn:ietf:params:jmap:mail" capability is missing; not only the `Email/set` call
- make the "urn:ietf:params:jmap:mail" capability implicit, so we can't run into an `unknownMethod` error

**Comment by rouazana** [comment]
Thanks, I addressed this point here: https://github.com/jmapio/jmap/pull/316/commits/f953dd3fb92cfc410d71919f410a2ac5d567c058#diff-a85095bca98d6fb8b1e3df07858d7f47R75
