### ISSUE TITLE
Why is the Invocation type an Array?

### ISSUE THREAD

**Issue by z0mbie42** [jmapio/jmap#322]
Hi,

I'm starting to evaluate JMAP for a service, but I have hard time understanding the rational behind why the `Invocation` type is an array.

So what are the reasons it couldn't have been an object like below?
```json
{
   "method": "",
   "params": {},
   "clientId": ""
}

// or 

{
   "clientId1": {
      "method": "",
      "params": {}
  }
}
```

**Comment by neilj** [comment]
The array representation of a tuple was considered easier to read over the wire (a surprisingly useful attribute when debugging), as it always preserved order (method name, then args).
