### ISSUE TITLE
VTODO support

### ISSUE THREAD

**Issue by tobiasgrosser** [jmapio/jmap#324]
The calendar SPEC clearly states it does not cover VTODO and VJOURNAL.

I use caldav synced TODO lists day in day out and would be very interested to see this feature to become part of JMAP. In particular, I feel this could be a great way to enable devices such as https://github.com/iSoron/uhabits/issues/104 to gain across-device support.

I wonder if anybody from the JMAP community could provide some feedback on the general thoughts in the JMAP community on TODOs in JMAP (and in general).

**Comment by neilj** [comment]
JMAP would be great for syncing todos. We just don't think that it should be in the same spec as calendars, because they are different features. We can't do everything at once so we're doing mail, contacts and calendars first.

**Comment by jaudriga** [comment]
@neilj: Does that mean even though JSCalendar supports tasks in the form of [JSTasks](https://datatracker.ietf.org/doc/html/draft-ietf-calext-jscalendar-32#section-2.2) your plan is to not include tasks in the [JMAP for Calendars](https://tools.ietf.org/html/draft-ietf-jmap-calendars-04#section-1) protocol? Might there be something like JMAP for tasks in the future?

**Comment by neilj** [comment]
That's right, it would be a separate JMAP for Tasks specification.

**Comment by jaudriga** [comment]
I have published a first version of JMAP for Tasks via #347.
