### ISSUE TITLE
Address lists vs. RFC's

### ISSUE THREAD

**Issue by equaeghe** [jmapio/jmap#33]
The `Message` object has a number of address (list) properties: `from`, `to`, `cc`, `bcc`, `replyTo`.

The `from` and `replyTo` properties are `Emailer` objects in the spec, and not arrays thereof, even though the RFC's allow multiple addresses in these fields. (I have used this and seen this elsewhere in the wild.)

A `sender` property (which should be a single `Emailer` property) seems to be missing.

N.B.: The example of the `Emailer` property seems to show an array of `Emailer` objects, no?

None of these fields say how ‘group syntax’ should be dealt with. (See [RFC6854](https://tools.ietf.org/html/rfc6854) for a recent RFC extending the use of this construct.)

**Comment by neilj** [comment]
Apologies for taking so long to get to this. While legal to have multiple addresses in From/Reply-To, we were going for simplicity (in the From case in particular, most clients will only ever care about one address). However, making these arrays allows clients that do care to easily access this data, while not making it too much more complex for others, and makes it consistent with the To/Cc etc. fields, so I've changed these to be arrays.

The sender property makes sense; I've added this.

Group and comment information must be stripped when converting to an Emailer object; I've updated the spec to note this. Most clients are not interested in this information, and it adds considerable complexity. The raw header can always be fetched instead and parsed locally should any client wish to get  information not included in the parsed format.

I've fixed the description of the example; well spotted!

Thanks for the great feedback.
