### ISSUE TITLE
bodyStructure on message/delivery-status

### ISSUE THREAD

**Issue by filiphanes** [jmapio/jmap#336]
Hi,
what is the correct behaviour when parsing `message/delivery-status` part into bodyStructure.
Does it behave like `multipart/*` or like one part without recursing into subparts?

**Comment by neilj** [comment]
The `message/delivery-status` content-type does not have subparts as part of the MIME structure, so there should be no recursion. [The body](https://tools.ietf.org/html/rfc3464#section-2.1) is in the format of a series of header fields, but as far as JMAP is concerned, this would be treated like any other body (with a blobId).
