### ISSUE TITLE
Future feature : quickly tell servers of a mail adress move

### ISSUE THREAD

**Issue by abda11ah** [jmapio/jmap#337]
There is one function that would be very useful and should exist in the future email protocol.
It is the automated migration of an email address.

For example, if I own the email address johndoe@example.com and with this address I register on 100 websites, the day I want to change my email address will be very tedious. Of course I can set up an automatic forwading of all the emails arriving on johndoe@example.com to my new mail adress while waiting to manually change the address on the 100 websites.

But if the future protocol had this function integrated : It could by a multicast message indicate to all these web servers that John Doe's email address has just changed. Each server receiving this specific configuration email would send a confirmation link that would allow these 100 websites to update very quickly the john doe's email adress.

Of course for this, these web servers will need a new special extension that is linked to the mail server.

Sorry for bad english, i'm french

**Comment by neilj** [comment]
That does sound interesting, although getting adoption could be difficult. However, it is well outside the scope of JMAP, which is just concerned with synchronisation between a client and server. If you have a concrete idea as to how this might be implemented, you are welcome to write a draft and bring it to the IETF to be discussed.

**Comment by abda11ah** [comment]
I don't have a lot of programming knowledge. I only worked a few programs in PHP to learn (as a hobby).

It's true that it will take some time to adopt but it's mostly the mail server that has to suggest this type of function if we want to see it exist one day.
