### ISSUE TITLE
Missing refs to RFC-8887 (JMAP over WebSockets) ?

### ISSUE THREAD

**Issue by chibenwa** [jmapio/jmap#346]
Hey there,

Having a look around, it seems like the RFC-8887 is missing a bit of visibility.

Should we add links/specs for it here as well as on https://github.com/jmapio/jmapio.github.io ?

(Work started on the Apache James server to support those.)

Benoit

**Comment by neilj** [comment]
I've updated https://jmap.io/spec.html to list this now.
