### ISSUE TITLE
Add WIP JMAP library?

### ISSUE THREAD

**Issue by judemille** [jmapio/jmap#354]
I've been working on a JMAP library for Rust, it's published [here on GitLab](https://gitlab.com/jmap-rs/rust-jmap), and I was wondering if it could be listed on the software page. Maybe under the Planned section?

**Comment by neilj** [comment]
Sure, looks great! Do you want to create a pull request to add it and I'll merge it.

**Comment by judemille** [comment]
Will do.

**Comment by judemille** [comment]
Actually, how would it be best to add it into the document? I'm not sure what the format would be for this case or what section.

**Comment by neilj** [comment]
@judemille I'm not sure which name is correct (jmap-rs, or rust-jmap, or ?), but I've made a PR with one way we could add it; does this work for you: https://github.com/jmapio/jmap/pull/356?

**Comment by marclaporte** [comment]
@neilj The current issue can be closed.
