### ISSUE TITLE
Does JMAP supports the FXP mode ?

### ISSUE THREAD

**Issue by abda11ah** [jmapio/jmap#379]
When you want to move a large amount of files between 2 FTP servers the process can be very long because you first have to download the files before sending them back to the second server.

File eXchange Protocol (FXP or FXSP) is a method of data transfer which uses [FTP](https://en.wikipedia.org/wiki/File_Transfer_Protocol) to transfer data from one remote server to another ([inter-server](https://en.wikipedia.org/wiki/Inter-server)) without routing this data through the client's connection.

The advantage of using FXP over FTP is evident when a high-bandwidth server demands resources from another high-bandwidth server, but only a low-bandwidth client, such as a network administrator working away from location, has the authority to access the resources on both servers. (Wikipedia)

Why not integrate this mechanism also in a mail server to be able to easily move tens of gigabytes between 2 mail servers.

**Comment by rjbs** [comment]
This seems like a suggestion for some specific mail server or perhaps an extension to JMAP (which would have to then be implemented in some mail server).  I think this is best left as an exercise for some interested party to try out and report back on.
