### ISSUE TITLE
Questions about JSON Pointer (result reference)

### ISSUE THREAD

**Issue by char-khan** [jmapio/jmap#382]
I have two questions.

Q1. Is this pointer invalid?
pointer: `/list/*/emailIds/2`
json:
```
"list": [
    { "emailIds": ["1", "2"] },
    { "emailIds": ["3"] },
    { "emailIds": ["4", "5"] }
]
```

Q2. Is it allowed to use "*" reference token more than once?
 For example, `/someArray/*/innerArray/*/someElement`.

**Comment by neilj** [comment]
> Q1. Is this pointer invalid? pointer: /list/*/emailIds/2

The pointer is valid, but evaluation will result in an error. It would succeed if all of the items in `list` had something defined at `[2]` (i.e. all have at least three items). See https://www.rfc-editor.org/rfc/rfc6901#section-4:

> […] will raise an error condition if it fails to resolve a concrete value for any of the JSON pointer's reference tokens.

> Q2. Is it allowed to use "*" reference token more than once?
> For example, /someArray/*/innerArray/*/someElement.

Yes, there is nothing in the spec that forbids this.

**Comment by char-khan** [comment]
Thank you for answering my question!
