### ISSUE TITLE
Ability to download original email content

### ISSUE THREAD

**Issue by jessicah** [jmapio/jmap#385]
Am trying to write a JMAP add-on for a client that expects emails to be stored as an RFC5322-compliant file. It will fetch and store headers only, and then expects to download the full RFC5322-compliant file on-demand.

**Comment by rjbs** [comment]
I don't know what you expect in reply to this.  There is no clear question in your issue.

Look into RFC 8620's section 6.2 on downloading binary data, and into the blobId property of email objects described in RFC 8621.

If that doesn't help, please clarify what it is you needed.

**Comment by jessicah** [comment]
Oh, the documentation wasn't very clear, that I could just grab blobId on the Email itself, instead of via body parts or bodyStructure.
