### ISSUE TITLE
Feature Request: Define way to discover JMAP URI

### ISSUE THREAD

**Issue by iNPUTmice** [jmapio/jmap#39]
Hi,

I recently discovered JMAP and I'm reading through the spec and other available information and there doesn't seem to be a way to discover the JMAP host when given an email address.

Other protocols like IMAP offer host discovery only via some extensions that usually aren't widely adopted. JMAP being a new protocol has the chance to add a standard way of discovering the host right into the specification.

Desired result: A client should be able to ask the user only for an email address and a password and figure out the JMAP host URI on it's own.

XMPP for example does this by using SRV records on the domain. For IMAP there are similar approaches.

When doing this it is also important that certificates are properly verifiable. Meaning since the email address is the only thing entered by a user the certificate on the HTTP host must match the domain name of the email address even though the JMAP URI might differ.

**Comment by robn** [comment]
There is a process, see: http://jmap.io/spec.html#service-autodiscovery

**Comment by iNPUTmice** [comment]
Sorry. I missed this somehow. Thanks for the hint.

Is there anything on how to validate certificates? In theory all hosts (loginURL, apiURl, ...) must present a valid certificate for the domain of the email address. Is this correct?

**Comment by neilj** [comment]
Well, once you have the authentication URL, everything is HTTPS, so you can use the standard CA system. (The Authentication URL should be secured with an SSL cert signed by a trusted CA, and ditto for the other endpoints you get after authentication).

If using auto discovery to find the authentication end point you have to rely on DNS, but the (current) solution to this is DANE.

**Comment by robn** [comment]
DANE isn't necessary. Assuming we trust the CA system, `.well-known` by itself is enough, even if the DNS is not secured. For name `user@example.com`, we visit https://example.com/.well-known/jmap. If the certificate offered is valid for `example.com`, then we can trust a redirect at that location to another site. That need not be at `example.com`, so long as it also offers a valid cert. In other words, HTTPS all the way through.

**Comment by neilj** [comment]
Ah yes, very true. I was just thinking of the other auto-discovery mechanism with SRV records.

**Comment by iNPUTmice** [comment]
Hi,

I understand the procedure for the case where the domain name of ``` https://example.com/.well-known/jmap``` matches the domain name of the email address. (```user@example.com```)

But what if the SRV lookup tells use to use ``` https://someotherhost.com:4430/.well-known/jmap```? In that case I can't verify the domain based on the domain of the email address. But I also can't really trust DNS. And DNSSEC isn't widely deployed. (And some doubt it ever will be.)

In any case I believe the spec should mention that when doing the SRV record lookup the result must be verified somehow. Either via DNSSEC (probably unlikely to happen any time soon) or by other means.
