### ISSUE TITLE
defaultAlerts should be OffsetTrigger

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#401]
For the **Calendar** properties `defaultAlertsWithTime` and `defaultAlertsWithoutTime` it might make sense to specify the **Alert** objects SHOULD / MUST be of \@type _OffsetTrigger_

**Comment by neilj** [comment]
It probably doesn't make much sense to use AbsoluteTrigger, but I'm not sure it's important enough to be worth mandating in the spec (especially given the spec is past the point we really want to be making semantic changes to it now). We also wouldn't want to preclude a future offset type, that might be relevant.

**Comment by dehart** [comment]
A guiding "SHOULD NOT" could make the intent more clear.
Added an AbsoluteTrigger will trigger an alert for every CalendarEvent with `useDefaultAlerts` at once.
