### ISSUE TITLE
CalendarEvent/get arguments

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#402]
The first line of 5.6. reads "three extra arguments" this should be "four extra arguments"

The arguments **recurrenceOverridesBefore** and **recurrenceOverridesAfter** limit the recurrenceOverrides the client would retrieve by `recurrenceId` and not the potentially patched `start`

If this is intended for clients that can interpret the `recurrenceRules` but do not cache all the data, there is an issue.
The patched `start` (or altered end) of an override can be within range while the `recurrenceId` is not.
Clients cannot be sure they aren't missing an override that should show when using these 2 arguments.

Example in this **CalendarEvent/get** request with a by-monthly event that will miss the override. The occurrence of 2025-01-01 is moved to 2024-12-01 but not retrieved.

Request
```
["CalendarEvent/query", {
    "accountId": "a0x9",
    "timeZone": "Australia/Melbourne",
    "filter": {
      "after": "2024-01-01T00:00:00",
      "before": "2024-12-31T23:59:59"
    }
  }, "2"],
  ["CalendarEvent/get", {
    "accountId": "a0x9",
    "#ids":{
      "resultOf":"3",
      "name":"CalendarEvent/query",
      "path":"/ids"
    },
    "recurrenceOverridesAfter":"2024-01-01T00:00:00",
    "recurrenceOverridesBefore":"2024-12-31T23:59:59"
  }, "3"]
]
```

Potential CalendarEvent object
```
{
  "id": "123",
  "title": "Every 2 months",
  "start": "2024-01-01T00:00:00",
  "recurrenceRules": [{
    "frequency": "monthly",
    "interval": 2,
  }],
  "recurrenceOverrides": {
     "2025-01-01T00:00:00": {
       "start": "2024-12-01T00:00:00"
     }
   }
}
```

PS: I hope I am not to late for findings to be useless it this point.

**Comment by neilj** [comment]
Thanks for the feedback.

> The first line of 5.6. reads "three extra arguments" this should be "four extra arguments"

Good catch, I'll fix that with the RFC editors, no problem.

> If this is intended for clients that can interpret the recurrenceRules but do not cache all the data, there is an issue.

This is more for clients to be able to request just data for specific recurrence-id(s) (e.g. they receive a push for a calendar alert that gives them the event id + recurrence id and they want to fetch minimal data to display it). You're right that the start time could be moved outside of this range, so in rare edge cases you would have insufficient data if trying to fetch the data for a specific time range. I think adding the ability to filter on this too would probably add more complexity than it's worth.
