### ISSUE TITLE
draft-ietf-jmap-mail: the requirement to have at least one mailbox

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#70]
2.3.4.  Destroying mailboxes

   There MUST always be *at least one* mailbox.  It is expected that the
   server will enforce this by setting "mayDeleteMailbox == false" on at
   least the Inbox, if not all system mailboxes.  However, if this is
   not the case, an attempt to destroy the last mailbox MUST still be
   rejected with a "mailboxRequired" error.

It is not clear why this is needed and what is this requirement trying to achieve.
Also need to consider a case of an account with only Shared Folders (in IMAP speak).

**Comment by neilj** [comment]
Looking at this again, I agree. I can't remember exactly why I added this, but I don't see why it wouldn't work if you start from a completely blank slate (you'd obviously have to create a mailbox before you could import any mail, but that's fine).
