### ISSUE TITLE
draft-ietf-jmap-mail: which mailbox properties are immutable?

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#72]
In 2.3.3:

  o  These properties are immutable or may only be set by the server:

      *  id

      *  role

      *  mustBeOnlyMailbox

      *  mayReadItems

      *  mayAddItems

      *  mayRemoveItems

      *  mayCreateChild

      *  mayRename

      *  mayDelete

      *  totalMessages

      *  unreadMessages

      *  totalThreads

      *  unreadThreads

Before the document is finished we should review this list. If a future specification adds support for ACL editing, some of these would become mutable.

**Comment by neilj** [comment]
The mayXXX properties tell you what *you* can do, which has to come from the server. Setting ACLs will be on a different property, as it will need to be a map from users to the ACLs you give them.
