### ISSUE TITLE
draft-ietf-jmap-mail: Need to say whether # references start from 0 or from 1

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#74]

**Comment by neilj** [comment]
Sorry, not entirely sure which bit of the spec you are referring to. '#' backreferences to refer to objects in the same API request are not numeric, so I presume it's not that. And the position argument in a message list is specified as being a "0-based index", so I think that's covered?

**Comment by neilj** [comment]
@aamelnikov Please reopen with clarification if you think there's still something that needs addressing here.
