### ISSUE TITLE
draft-ietf-jmap-mail: support for "width" and "height"

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#77]
In Section 5:

   o  *width*: "Number|null" The width (in px) of the image, if the
      attachment is an image.

   o  *height*: "Number|null" The height (in px) of the image, if the
      attachment is an image.

Does these have to be mandatory to support? This raises implementation complexity.

**Comment by neilj** [comment]
Yeh, this definitely needs to be optional.
