### ISSUE TITLE
draft-ietf-jmap-mail: does description property need an associated language tag?

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#81]

**Comment by neilj** [comment]
I don't feel it does, although I have clarified that when intended to be shown to the end user it may be localised by the server if the server knows the user's preferred language. Unless the server is returning multiple versions of a string, so an associated language tag allows the client to choose the most appropriate one, I don't feel there's a great deal of value in it. The client will just display the message regardless. 

(NB The only place this is currently relevant is the `forbiddenToSend` error in EmailSubmission.)
