### ISSUE TITLE
draft-ietf-jmap-core: privacy considerations

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#83]
In Section 2.2:
   o  *clientVersion*: "String" Information to identify the version of
      the client.  This MUST change for any changed client code (e.g. a
      version control tag or counter for development software) and
      SHOULD sort lexically later for newer versions.

   o  *deviceName*: "String" A human-friendly string to identify the
      device making the request, e.g.  "Joe Blogg's iPhone".

Are any of these optional?

Also, these have privacy considerations, that should be discussed in the document.

**Comment by neilj** [comment]
As auth has been punted this text is gone from the spec.
