### ISSUE TITLE
draft-ietf-jmap-core: exponential backoff for "service unavailable" needs to be defined in more details

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#87]
2.3.5.  503: Service unavailable

   The server is currently down.  Try again later with exponential
   backoff.  There is no content in the response.

This should probably provide some recommendations on how many times to try and for how long.

**Comment by neilj** [comment]
As per the HTTP-WG best practices, I'm removing the list of HTTP response codes from the spec; clients should just handle as per the HTTP standard.
