### ISSUE TITLE
draft-ietf-jmap-core: missing reference for oauth

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#88]
2.4.2.  401: Unauthorized

   Failed due to missing "Authorization" header, or the "Authorization"
   header did not contain a valid access token.  As per the HTTP spec,
   the response MUST have a "WWW-Authenticate: Bearer" header.  There is

This should also have a reference to the OAuth spec where "Bearer" is defined.

   no content in the response.

**Comment by robn** [comment]
Probably RFC6750?

**Comment by neilj** [comment]
We've removed authentication from the spec so this is no longer relevant.
