### ISSUE TITLE
draft-ietf-jmap-core: do we need a registry (or registries) of error types?

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#89]
3.3.  Errors

   Possible errors for each method are specified in the method
   descriptions.  If a method encounters an error, the appropriate
   "error" response MUST be inserted at the current point in the output

Do we need an IANA registry of error codes? (I.e. is the list of errors fixed or is it extensible).

If the list is extensible: does each method have its own list of error types or are they all in the same namespace?

   array and, unless otherwise specified, further processing MUST NOT
   happen within that method call.

**Comment by neilj** [comment]
The feedback I've had off-list is this is probably *not* necessary. I have gone through [RFC 5530](https://tools.ietf.org/html/rfc5530) to make sure any relevant errors are covered in the spec, and the consensus seemed to be it was unlikely that entirely new classes of error were likely to appear. It greatly helps client authors to know the complete set of errors that may be returned to ensure everything is handled in an appropriate manner. This should make that easier.

The error codes are not namespaced and the spec gives all permissible error results. There are a set of errors that any method may return where appropriate, and each method may define further errors that can be returned, which are specific to that method.

**Comment by cjnewman** [comment]
Machine readable protocol errors are useful when different client behaviors can be articulated based on the distinction between those errors. The advantage to creating a registry is it makes it easier to add new ones of these. If you don't create an easy-to-extend error registry, then your initial error set becomes relatively static and semantic overload can happen. IMAP did need to add some (in RFC 5530), but outside the authentication process, the temporary-vs.-permanent distinction, and exists/not-exists codes, the distinctions just don't seem that important for machine readability (on the flip side, having arbitrary human readable text is incredibly useful for all troubleshooting).

If the rough consensus is towards a registry, I think issue #210 needs to be addressed first and then I can write up the text.

Regardless, we'll need to deal with reserving the 'urn:ietf:params:jmap:error' prefix which begs the question of whether the capabilities should be moved under a 'capa' prefix, such as: 'urn:ietf:params:jmap:capa:core' and 'urn:ietf:params:jmap:capa:mail' or should we just reserve the 'error' capability as a not advertised capability used for errors in the base spec.

**Comment by neilj** [comment]
So, I'm still not sure on whether the consensus is to have a registry or not; I agree it's only useful when you can articulate the client behaviours.

Regarding the URNs, my preference is we just reserve the 'error' capability as a not advertised capability used for errors in the base spec.

**Comment by neilj** [comment]
Resolved by #246
