### ISSUE TITLE
draft-ietf-jmap-core: opt-in for vendor specific extensions

### ISSUE THREAD

**Issue by aamelnikov** [jmapio/jmap#90]
3.4.  Vendor-specific extensions

   Individual services will have custom features they wish to expose
   over JMAP.  This may take the form of extra datatypes and/or methods
   not in the spec, or extra arguments to JMAP methods, or extra
   properties on existing data types (which may also appear in arguments
   to methods that take property names).  To ensure compatibility with
   clients that don't know about a specific custom extension, and for
   compatibility with future versions of JMAP, the server MUST ONLY
   expose these extensions if the client explicitly opts in.

I think this section needs a bit more explanation on way(s) to opt-in. Possibly it is enough to have some pointers to text elsewhere in the document.

   Without
   opt-in, the server MUST follow the spec and reject anything that does
   not conform to it as specified.

**Comment by neilj** [comment]
Resolved by a0be25999a547d085053f0d16b73db13beee53a3
