### ISSUE TITLE
recurrenceOverrides property

### ISSUE THREAD

**Issue by dehart** [jmapio/jmap#96]
Only recurring events can have recurrenceOverrides
To restrict this the recurrenceOverrides could be in the Recurrence object.

eg CalendarEvent->recurrenceRule->recurrenceOverrides
instead of CalendarEvent->recurrenceOverrides

any reason why it shouldn't?

**Comment by rsto** [comment]
A calendar event might be recurring, but not require a Recurrence object. E.g. the recurrenceOverrides would then be an object with the recurrence datetime as key and an empty object.

The iCalendar equivalent to this is RDATE (see [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.8.5.2)), whereas the Recurrence object maps an iCalendar RRULE.

**Comment by dehart** [comment]
You are right, my mistake
