### ISSUE TITLE
getMessageListUpdates behaviour for threads.

### ISSUE THREAD

**Issue by iNPUTmice** [jmapio/jmap#98]
The behaviour of `getMessageListUpdates` in regards to threads seems a bit under specified and I have a couple of questions.

Can `getMessageListUpdates` only be used to update the list of threads or does it simultaneously update the list of message ids within a thread? In case of the later how do I know the position of the message within a thread since index refers to the position of the thread within the list of threads?
If however `getMessageListUpdates` can only be used to update the list of threads am I right in assuming that `RemovedItem[]` will remove single messages from threads? Meaning I will have to keep track of all messages ids within a thread and when a thread has an empty message list (and only then) I can discard that thread from the thread list? Or to put it in other words. If a thread contains two messages and I remove one of them will that message appear as a `RemovedItem[]`? Or what happens if that entire thread is removed? Will the update have two `RemovedItem`s? Even when collapse threads is true?

**Comment by neilj** [comment]
If you want to fetch the list of message ids in a thread, you should fetch the `Thread` object (call `getThreads` with the thread id). If the set of messages in a thread changes, then the thread id will be returned in a call to `getThreadUpdates` (which takes an argument to allow you to optionally fetch the `Thread` object immediately as well).

The `MessageList` is a query on the set of messages, normally equivalent to a mailbox listing. So `getMessageListUpdates` is for updating this list of messages/threads. It does *not* say anything about which messages are in a thread. For example, you may have a message in the inbox, which gets moved to an archive folder. The message will appear in the `removed` array of `getMessageListUpdates` with a filter to get the list of messages just in the inbox. However, the message is still in the same thread; the thread itself has not changed. If you are showing the user their inbox though, you will apply the update and the thread will no longer appear in the list.

You cannot get a thread with an empty message list. If the last message in the thread is destroyed, the thread itself is considered destroyed so will appear in the `removed` list in the response to `getThreadUpdates`.

Does that clarify things for you?

**Comment by iNPUTmice** [comment]
Hi @neilj 

thank you for getting back to me. That doesn't answer my question though.
Let me give you a concrete example of what I'm getting at.
Assuming I want to display the Inbox threaded. The user has a thread T1 with the messages M1 and M2 and a thread T2 with the message M3. Now the user archives messages M2. I'm assuming the desired result is that T1 will still show in the inbox. However if I understood you and the documentation correctly a call to `getMessagesListUpdates` will a contain a removedItem with messageId=M2 and threadId=T1.
How do I know by looking at that update that T1 is still part of the Inbox even though it's threadId is part of a removedItem?

**Comment by neilj** [comment]
So, I'm going to suppose you're displaying this with `collapseThreads: true` and sorted newest first.

Your initial message list would be: `[M1/T1, M3/T2]`
You then archive just M1, and the update would tell you to remove `M1/T1`, and add `M2/T1` (and tell you the index of where to add it).

If you were not collapsing threads, your initial message list would be: `[M1/T1,M2/T1,M3/T2]`. If you archive M1, the update would just have remove `M1/T1`.

So in either case, T1 is still in the resulting message list.

**Comment by iNPUTmice** [comment]
> …  and add `M2/T1` (and tell you the index of where to add it).

Oh that does make a lot of sense. I didn't get that before. Thank you for clarifying that.

I don't think neither the wording nor the examples in the spec for `getMessageListUpdates` describe that properly.

**Comment by neilj** [comment]
We'll definitely add more examples to the spec before it's final. Thanks for the feedback.

**Comment by iNPUTmice** [comment]
I have one more question.

> update would tell you to remove `M1/T1`, and add `M2/T1` (and tell you the index of where to add it

So essentially a MessageList is a list of messageId-threadId tuples? Am I correct in assuming that the `messageIds` array and the `threadIds` array of the messageList response are always the same length and I could construct the same kind of tuples from that? `Tuple(messagesId[n],threadIds[n])`

**Comment by neilj** [comment]
Yes, that's correct.
